// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_21 = "CgkIzo7z3poMEAIQFQ"; // <GPGSID>
        public const string achievement_tv = "CgkIzo7z3poMEAIQFw"; // <GPGSID>
        public const string achievement_15 = "CgkIzo7z3poMEAIQDw"; // <GPGSID>
        public const string achievement_11 = "CgkIzo7z3poMEAIQCw"; // <GPGSID>
        public const string achievement_22 = "CgkIzo7z3poMEAIQFg"; // <GPGSID>
        public const string achievement_13 = "CgkIzo7z3poMEAIQDQ"; // <GPGSID>
        public const string achievement_17 = "CgkIzo7z3poMEAIQEQ"; // <GPGSID>
        public const string achievement_25 = "CgkIzo7z3poMEAIQGg"; // <GPGSID>
        public const string achievement_18 = "CgkIzo7z3poMEAIQEg"; // <GPGSID>
        public const string achievement_12 = "CgkIzo7z3poMEAIQDA"; // <GPGSID>
        public const string achievement_9 = "CgkIzo7z3poMEAIQCQ"; // <GPGSID>
        public const string achievement_2 = "CgkIzo7z3poMEAIQAg"; // <GPGSID>
        public const string achievement_3 = "CgkIzo7z3poMEAIQAw"; // <GPGSID>
        public const string achievement = "CgkIzo7z3poMEAIQAQ"; // <GPGSID>
        public const string achievement_6 = "CgkIzo7z3poMEAIQBg"; // <GPGSID>
        public const string achievement_7 = "CgkIzo7z3poMEAIQBw"; // <GPGSID>
        public const string achievement_4 = "CgkIzo7z3poMEAIQBA"; // <GPGSID>
        public const string achievement_5 = "CgkIzo7z3poMEAIQBQ"; // <GPGSID>
        public const string achievement_20 = "CgkIzo7z3poMEAIQFA"; // <GPGSID>
        public const string achievement_8 = "CgkIzo7z3poMEAIQCA"; // <GPGSID>
        public const string achievement_10 = "CgkIzo7z3poMEAIQCg"; // <GPGSID>
        public const string achievement_23 = "CgkIzo7z3poMEAIQGA"; // <GPGSID>
        public const string achievement_24 = "CgkIzo7z3poMEAIQGQ"; // <GPGSID>
        public const string achievement_16 = "CgkIzo7z3poMEAIQEA"; // <GPGSID>
        public const string achievement_14 = "CgkIzo7z3poMEAIQDg"; // <GPGSID>
        public const string achievement_19 = "CgkIzo7z3poMEAIQEw"; // <GPGSID>

}

